# Generated by Django 4.2 on 2023-04-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obludarium', '0002_alter_atlet_procenta_tuku_alter_atlet_vaha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'uživatel',
                'verbose_name_plural': 'uživatelé',
            },
        ),
        migrations.AlterModelOptions(
            name='atlet',
            options={'verbose_name': 'Atlet', 'verbose_name_plural': 'Atleti'},
        ),
        migrations.AlterModelOptions(
            name='vykon',
            options={'verbose_name': 'Výkon', 'verbose_name_plural': 'Výkony'},
        ),
    ]
