# Generated by Django 4.2 on 2023-04-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obludarium', '0003_uzivatel_alter_atlet_options_alter_vykon_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(max_length=30, verbose_name='Tagy')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tagy',
            },
        ),
        migrations.AddField(
            model_name='atlet',
            name='tagy',
            field=models.ManyToManyField(to='obludarium.tag'),
        ),
    ]
